# HCM runtime configuration

HCM_HOME=/root/hcm/19_mqtt_remote_config
MODULE_DIR=/root/hcm/modules_project
APP_PATH=/root/hcm/19_mqtt_remote_config/lv_hcm_test

BROKER_HOST=10.175.22.126
BROKER_PORT=1883

APP_LOG=/tmp/hcm_app.log
